### ISSUE TITLE
Problem with automatic updating of certain entities

### ISSUE THREAD

**Issue by ShagoY** [Jezza34000/homeassistant_petkit#23]
## System Information

version | core-2025.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.2
Stage | running
Available Repositories | 1501
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 5, 2025 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | eu-central-1-24.ui.nabu.casa
certificate_status | ready
instance_id | 11e5cbbfaffe447a8ee0451dd0007938
can_reach_cert_server | pending
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 60.3 GB
disk_used | 29.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.18.0), Samba share (12.3.2), Log Viewer (0.17.1), Terminal & SSH (9.16.0), Node-RED (19.0.0), Advanced SSH & Web Terminal (20.0.0), ESPHome Device Builder (2024.12.2), Grafana (10.2.2), File editor (5.8.0), chrony (5.0.0), InfluxDB (5.0.1), Portainer (2.25.1), MariaDB (2.7.2), phpMyAdmin (0.11.0), MyElectricalData (0.13.2), Zigbee2MQTT (1.42.0-2), Mosquitto broker (6.4.1), Glances (0.21.1), DbStats (0.5.11)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 30
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 29, 2024 at 19:49
-- | --
current_recorder_run | January 13, 2025 at 10:28
estimated_db_size | 2703.16 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Integration version ?

1.4.3

### Device type

Feeder, Fountain

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Jezaa34000/homeassistant_petkit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi Jezza,

Since updating to 1.4.3 (Installed last week on January 09), I have entities that are not updated automatically unlike others.
A restart/reboot usually refreshes them.

I deleted everything and reauthenticated, and tried 1.5.0... Nothing seems to improve the issue.  

For example, you can see that “Pet Feeder Times eaten” is no longer updated, while “Pet Feeder Eating” displays the correct data.

![{23848EEC-C98E-4C62-8728-AD7FCF3996AA}](https://github.com/user-attachments/assets/beec38b1-b302-46b6-a81b-5dc45813579f)

I had this problem with your first versions. It was because of my fountain. Do you think it could still be the case?

Regards.

**Comment by Jezza34000** [comment]
Hi, no the problem is identified and will be fixed in next release :-)

**Comment by ShagoY** [comment]
Well, I'll stop debugging  :-D
Do we agree that 1.5.0 is also buggy?

**Comment by Jezza34000** [comment]
Yes

**Comment by mihaicristianpetrescu** [comment]
Same issue identified here, in my case it seems like only the images from the YumShare Dual Hopper are updated, the rest of the entities provided remain with the last known value when a force reload has been triggered.

Also the "Pet" model is always returning: Last use duration = 0 and Last weight measurement = 0.0 kg

**Comment by Jezza34000** [comment]
Hi @mihaicristianpetrescu, @ShagoY 
This issue is fixed in this version
https://github.com/Jezza34000/homeassistant_petkit/releases/tag/1.5.0

**Comment by mihaicristianpetrescu** [comment]
Installed and testing...
Still have the "Also the "Pet" model is always returning: Last use duration = 0 and Last weight measurement = 0.0 kg" problem. It was working fine on the other HACS integration.

Seems like the entities have started to update after events happen, not the fastest but they seem to update.
Will confirm with some additional ones. (ex: Times eaten, Times dispensed, Manually Dispensed Hopper 2)

**Comment by Jezza34000** [comment]
What about picture display of last event ? Is it working ok ?

**Comment by mihaicristianpetrescu** [comment]
> What about picture display of last event ? Is it working ok ?

My cat just decided to take a stroll right now in front of it and yes I can confirm it updated all 3 instances of "last..." images. 
However, "Last feed" event wasn't updated until the "last visit" event wasn't registered.
Will need to keep an eye on this.

**Comment by mihaicristianpetrescu** [comment]
@Jezza34000 Seems like "Last feed event" and "Last eat event" are not updating accordingly. They are left "behind".
"Last visit event" seems to be updating though.

**Comment by Jezza34000** [comment]
@mihaicristianpetrescu ok
I need more information :
-What is the feeder model ?
-Can you give me the 3 pictures you have in Homeassistant for the 3 event?
-Can you give me a screenshot of applications with all three section : Visit, Eat, Feed
make sure to take the screenshot of the application at the moment when the highlight of the video starts, because as you may have noticed in the application the video plays automatically, the still image retrieved in home assistant is the very first image of this same video.

**Comment by ShagoY** [comment]
Hello Jezza,
I don't seem to have any problems with the images, they seem to update well.
However, the RSSI sensor seems to stop updating by period only.

Here are the statistics since this morning:
![{AE83A424-1621-4A0C-9F10-410ABD0A7623}](https://github.com/user-attachments/assets/1fe58bed-bdc6-4e2b-9df8-77edb82b4416)

**Comment by ShagoY** [comment]
I've just seen that it finally looks the same as before... 
So it's probably normal.

**Comment by Jezza34000** [comment]
The RSSI looks normal because during the night no one moves in the house the link remains more stable, it looks like you wake up around 8am ;-)

**Comment by ShagoY** [comment]
I would add that Pet Feeder Times eaten is now well synchronized.

**Comment by Jezza34000** [comment]
No update @mihaicristianpetrescu  ? i close this issue ?

**Comment by mihaicristianpetrescu** [comment]
> [@mihaicristianpetrescu](https://github.com/mihaicristianpetrescu) ok I need more information : -What is the feeder model ? -Can you give me the 3 pictures you have in Homeassistant for the 3 event? -Can you give me a screenshot of applications with all three section : Visit, Eat, Feed make sure to take the screenshot of the application at the moment when the highlight of the video starts, because as you may have noticed in the application the video plays automatically, the still image retrieved in home assistant is the very first image of this same video.

Model: YumShare Dual Hopper (D4SH)

From HA:
<img width="317" alt="Image" src="https://github.com/user-attachments/assets/4905c68a-0291-45f3-92a4-ccdce723253a" />

From APP:
<img width="321" alt="Image" src="https://github.com/user-attachments/assets/e9a0f960-0ac6-4bb7-a9a7-814506e023a1" />

Last eat event - updated 1h ago
Last feed event - updated 1h ago
Last visit event - updated 2 min ago

**Comment by Jezza34000** [comment]
@mihaicristianpetrescu with the little information provided I am unable to determine if there is a bug or not? as already asked in my last message: Can you give me a screenshot of applications with all three section : Visit, Eat, Feed ? (and the picture not only the hours)

**Comment by mihaicristianpetrescu** [comment]
@Jezza34000 Not sure what you mean by "screenshot of applications with all 3 sections".
The mobile app has a Facebook like stream of events with timestamp, event + image (I captured this in From APP - that's the most recent event registered, the other 2 were registered 3-4 hours before).
For privacy reasons I don't want to share the images here since it's a public space.

**Comment by Jezza34000** [comment]
I understand, can you send me messages directly on discord? The link is available on the README

**Comment by mihaicristianpetrescu** [comment]
True. I could also blur the images, not sure what you're looking for/at more exactly.

**Comment by Jezza34000** [comment]
Try also the new pre-release : https://github.com/Jezza34000/homeassistant_petkit/releases/tag/1.6.0
I've modified many stuff in picture management and display
Let me know if it's change something for you ?

**Comment by Jezza34000** [comment]
@mihaicristianpetrescu  Still occur with last update 1.6.1 or solved ?

**Comment by mihaicristianpetrescu** [comment]
@Jezza34000 I just updated this morning. Need to observe it for a bit.
I also have a Fountain connected via BT relay of the Feeder and that doesn't seem to respect the polling rate. Now it's been last updated 1 hour ago even thought it's set to 15 min and previously it was set to 30 min.
Initially after the update the 3 images from the Feeder appeared to have been updated, however the timestamp next to them was displaying "Unknown" for a while until they managed to finally get updated.

Is there a way to access the live video feed? The other addon, if I recall correctly, allowed for such access.
Also, different issue, but if you have a "pet" declared, it appears as a sensor and it has 2 entities:
"Last use duration" and "Last weight measurement", both of which are always displaying 0.
In the other addon they both had correct values.

**Comment by Jezza34000** [comment]
Hi, we are on a thread concerning the subject "Problem with automatic updating of certain entities" we will stay on this single subject please.
For the other 3 questions, please come to Discord to discuss them or open other threads. This will avoid treating these subjects here and not being able to benefit others because they have nothing to do with the main subject and therefore almost impossible to find

**Comment by Jezza34000** [comment]
Can we close this issue ? Did you have enough time to try ? @mihaicristianpetrescu

**Comment by mihaicristianpetrescu** [comment]
Seems like it pretty much works. There's certainly a delay with the images updates. I'll keep an eye out but feel free to close it for now, thank you! :)

**Comment by Jezza34000** [comment]
Good @mihaicristianpetrescu : About the delay it can be configured with the "Configure" button. By default update occur every 15 minutes, it's slow... but this feature uses : network and system resources to download & decrypt videos and images this is to avoid excess usage of this ressources  :-)

**Comment by mihaicristianpetrescu** [comment]
Hmm you're saying videos...where are those available for viewing? And yes I understand there's a delay since it's a polling mechanism working behind the scenes to provide updates.

**Comment by Jezza34000** [comment]
Look into Media section into Homeassistant you can access all video and pictures from your devices. (If you have enabled it in Configuration)
